---

- hosts: 127.0.0.1
  gather_facts: no
  roles:
    - 00setup

- hosts: all
  gather_facts: no
  tasks:
  #- name: include targetprofile specific variables and environment variables
  #  include_vars: env_vars/{{ targetprofile|upper }}.yml
  roles:
    - common
    #- ccf_tenant
