---

- debug:
    msg: "This always displays"
    #when: ansible_default_ipv4.gateway is defined

- debug:
    msg: "This only displays with ansible-playbook -vv+"
    verbosity: 2

- name: Get uptime information
  ansible.builtin.shell: /usr/bin/uptime
  register: result

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2

- name: Hello World
  command: echo "Hello World!"
  register: helloworld

- debug: var=helloworld.stdout

- name: debug unencrypted var from config dir
  ansible.builtin.debug:
    var: this.isa.varname

- name: Bare include (free-form) unencrypted.yml vars file
  include_vars: "{{playbook_dir}}/../dassaultConfig/afolder/unencrypted.yml"

- name: Bare include vault encrypted file
  include_vars: "{{playbook_dir}}/../dassaultConfig/afolder/avarsfile.yml"

- name: debug encrypted var from config dir (should be 'two')
  #when: inventory_hostname in groups['myowncomputer']
  when: inventory_hostname == '0.0.0.0'
  debug:
    msg: "secret value {{some.structure.anArray[1]}}"
