---

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    customYaml:
      customRoot:
      - first: "first Value"
        name: "first name"
      - second: "second Value"
        name: "second name"
      - third: "third Value"
        name: "third name"

  # ansible will search dir filter_plugins/ by default on the same level as the playbook
  # to have a "global" directory add the filter_plugins search dir to ansible.cfg
  # e.g. if at the project root
  # filter_plugins = ./filter_plugins
  tasks:
  - name: custom filter
    debug:
      msg: "{{ 'test' | a_filter }}"
  - name: custom filter with params
    debug:
      msg: "{{ 'test' | another_filter('the','filters') }}"

  - name: original customYaml
    debug:
      msg: "\n{{ customYaml | to_nice_yaml(2) }}\n"
  - name: original customJson
    debug:
      msg: "\n{{ customYaml | to_nice_json }}\n"
  - name: jq filter
    set_fact:
      transformedYaml: '{{ customYaml | to_json | jq("[.customRoot[].name]") }}'
  - name: jq raw result
    debug:
      msg: "\n{{ transformedYaml }}\n"
  - name: jq nice result
    debug:
      msg: "\n{{ transformedYaml | to_nice_yaml }}\n"
  - name: something
    debug:
      msg: "{{ transformedYaml[0] }}"